// <auto-generated />
using System;
using Marshal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Marshal.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MarshalDbContext))]
    [Migration("20260919090000_DostepDoKalendarza")]
    partial class DostepDoKalendarza
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Marshal.Domain.Areas.Area", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("CalendarId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultNudgeDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuietDays")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SortOrder")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.HasIndex("Deleted");

                    b.HasIndex("SortOrder");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Attachments.Attachment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.HasIndex("Sha256");

                    b.HasIndex("TaskId");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Calendar.CalendarCursor", b =>
                {
                    b.Property<string>("SourceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("FetchedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncToken")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("SourceId");

                    b.ToTable("CalendarCursors", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Calendar.CalendarEvent", b =>
                {
                    b.Property<string>("SourceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndsAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartsAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("SourceId", "ExternalId");

                    b.HasIndex("StartsAt");

                    b.ToTable("CalendarEvents", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Calendar.CalendarSource", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Account")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CalendarSources", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Contacts.Contact", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Deleted");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Diagnostics.ActivityEntry", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("ActivityEntries", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Filters.SavedFilter", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("SortOrder")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("SavedFilters", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Notes.Note", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromTaskId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("IsPinned");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Projects.Project", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentProjectId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<double>("SortOrder")
                        .HasColumnType("REAL");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("ParentProjectId");

                    b.HasIndex("State");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Review.ReviewSession", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessedIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.ToTable("ReviewSessions", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Sync.ChangeEntry", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hlc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Sent", "Hlc");

                    b.ToTable("Changes", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Sync.FieldStamp", b =>
                {
                    b.Property<string>("EntityType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hlc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("EntityType", "EntityId", "Field");

                    b.ToTable("FieldStamps", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Sync.LocalSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("LocalSettings", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Sync.ReminderShown", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("ReminderAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ShownAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskId", "ReminderAt");

                    b.ToTable("ReminderShown", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Sync.SyncCursor", b =>
                {
                    b.Property<string>("RemoteDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSegment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("RemoteDeviceId");

                    b.ToTable("SyncCursors", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Tags.Tag", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("SortOrder")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Tags.TaskTag", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskTags", (string)null);
                });

            modelBuilder.Entity("Marshal.Domain.Tasks.TaskItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CarriedSince")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DeferUntil")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DoDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("DoTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("FocusDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FocusMissCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentTaskId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrenceJson")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReminderAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReminderLeadsCsv")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RollCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SharedCalendarId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedEventId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("SortOrder")
                        .HasColumnType("REAL");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WaitingForWho")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WaitingNudgeDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("WaitingSince")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Deadline");

                    b.HasIndex("DoDate");

                    b.HasIndex("FocusDate");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("Priority");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReminderAt");

                    b.HasIndex("SharedCalendarId");

                    b.HasIndex("State");

                    b.HasIndex("State", "DoDate");

                    b.ToTable("Tasks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
