// <auto-generated />
using System;
using System.Reflection;
using Marshal.Domain.Calendar;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Marshal.Infrastructure.Data.Compiled
{
    [EntityFrameworkInternal]
    public partial class CalendarCursorEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Marshal.Domain.Calendar.CalendarCursor",
                typeof(CalendarCursor),
                baseEntityType,
                propertyCount: 3,
                keyCount: 1);

            var sourceId = runtimeEntityType.AddProperty(
                "SourceId",
                typeof(Guid),
                propertyInfo: typeof(CalendarCursor).GetProperty("SourceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CalendarCursor).GetField("<SourceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 36,
                valueConverter: new GuidToStringConverter());
            sourceId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");

            var fetchedAt = runtimeEntityType.AddProperty(
                "FetchedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(CalendarCursor).GetProperty("FetchedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CalendarCursor).GetField("<FetchedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new DateTimeOffsetConverter());
            fetchedAt.SetSentinelFromProviderValue(0L);

            var syncToken = runtimeEntityType.AddProperty(
                "SyncToken",
                typeof(string),
                propertyInfo: typeof(CalendarCursor).GetProperty("SyncToken", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CalendarCursor).GetField("<SyncToken>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);

            var key = runtimeEntityType.AddKey(
                new[] { sourceId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "CalendarCursors");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
