// <auto-generated />
using Marshal.Infrastructure.Data;
using Marshal.Infrastructure.Data.Compiled;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(MarshalDbContext), typeof(MarshalDbContextModel))]
