// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Marshal.Infrastructure.Data.Compiled
{
    public partial class MarshalDbContextModel
    {
        private MarshalDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("aa7cb364-b4aa-47e6-af64-0cd170e5d7e6"), entityTypeCount: 19)
        {
        }

        partial void Initialize()
        {
            var area = AreaEntityType.Create(this);
            var attachment = AttachmentEntityType.Create(this);
            var calendarCursor = CalendarCursorEntityType.Create(this);
            var calendarEvent = CalendarEventEntityType.Create(this);
            var calendarSource = CalendarSourceEntityType.Create(this);
            var contact = ContactEntityType.Create(this);
            var activityEntry = ActivityEntryEntityType.Create(this);
            var savedFilter = SavedFilterEntityType.Create(this);
            var note = NoteEntityType.Create(this);
            var project = ProjectEntityType.Create(this);
            var reviewSession = ReviewSessionEntityType.Create(this);
            var changeEntry = ChangeEntryEntityType.Create(this);
            var fieldStamp = FieldStampEntityType.Create(this);
            var localSetting = LocalSettingEntityType.Create(this);
            var reminderShown = ReminderShownEntityType.Create(this);
            var syncCursor = SyncCursorEntityType.Create(this);
            var tag = TagEntityType.Create(this);
            var taskTag = TaskTagEntityType.Create(this);
            var taskItem = TaskItemEntityType.Create(this);

            AreaEntityType.CreateAnnotations(area);
            AttachmentEntityType.CreateAnnotations(attachment);
            CalendarCursorEntityType.CreateAnnotations(calendarCursor);
            CalendarEventEntityType.CreateAnnotations(calendarEvent);
            CalendarSourceEntityType.CreateAnnotations(calendarSource);
            ContactEntityType.CreateAnnotations(contact);
            ActivityEntryEntityType.CreateAnnotations(activityEntry);
            SavedFilterEntityType.CreateAnnotations(savedFilter);
            NoteEntityType.CreateAnnotations(note);
            ProjectEntityType.CreateAnnotations(project);
            ReviewSessionEntityType.CreateAnnotations(reviewSession);
            ChangeEntryEntityType.CreateAnnotations(changeEntry);
            FieldStampEntityType.CreateAnnotations(fieldStamp);
            LocalSettingEntityType.CreateAnnotations(localSetting);
            ReminderShownEntityType.CreateAnnotations(reminderShown);
            SyncCursorEntityType.CreateAnnotations(syncCursor);
            TagEntityType.CreateAnnotations(tag);
            TaskTagEntityType.CreateAnnotations(taskTag);
            TaskItemEntityType.CreateAnnotations(taskItem);

            AddAnnotation("ProductVersion", "10.0.11");
        }
    }
}
