// <auto-generated />
using System;
using System.Reflection;
using Marshal.Domain.Sync;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Marshal.Infrastructure.Data.Compiled
{
    [EntityFrameworkInternal]
    public partial class ReminderShownEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Marshal.Domain.Sync.ReminderShown",
                typeof(ReminderShown),
                baseEntityType,
                propertyCount: 3,
                keyCount: 1);

            var taskId = runtimeEntityType.AddProperty(
                "TaskId",
                typeof(Guid),
                propertyInfo: typeof(ReminderShown).GetProperty("TaskId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReminderShown).GetField("<TaskId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 36,
                valueConverter: new GuidToStringConverter());
            taskId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");

            var reminderAt = runtimeEntityType.AddProperty(
                "ReminderAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ReminderShown).GetProperty("ReminderAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReminderShown).GetField("<ReminderAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueConverter: new DateTimeOffsetConverter());
            reminderAt.SetSentinelFromProviderValue(0L);

            var shownAt = runtimeEntityType.AddProperty(
                "ShownAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ReminderShown).GetProperty("ShownAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReminderShown).GetField("<ShownAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new DateTimeOffsetConverter());
            shownAt.SetSentinelFromProviderValue(0L);

            var key = runtimeEntityType.AddKey(
                new[] { taskId, reminderAt });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ReminderShown");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
