// <auto-generated />
using System;
using System.Reflection;
using Marshal.Domain.Sync;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Marshal.Infrastructure.Data.Compiled
{
    [EntityFrameworkInternal]
    public partial class SyncCursorEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Marshal.Domain.Sync.SyncCursor",
                typeof(SyncCursor),
                baseEntityType,
                propertyCount: 2,
                keyCount: 1);

            var remoteDeviceId = runtimeEntityType.AddProperty(
                "RemoteDeviceId",
                typeof(string),
                propertyInfo: typeof(SyncCursor).GetProperty("RemoteDeviceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncCursor).GetField("<RemoteDeviceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 64);

            var lastSegment = runtimeEntityType.AddProperty(
                "LastSegment",
                typeof(string),
                propertyInfo: typeof(SyncCursor).GetProperty("LastSegment", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncCursor).GetField("<LastSegment>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 32);

            var key = runtimeEntityType.AddKey(
                new[] { remoteDeviceId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "SyncCursors");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
